"""
从 web/backend/schemas.py 自动生成前端 TypeScript 类型定义。
"""
from __future__ import annotations

import argparse
import sys
from pathlib import Path
from typing import Any

from pydantic import BaseModel

ROOT = Path(__file__).resolve().parents[1]
if str(ROOT) not in sys.path:
    sys.path.insert(0, str(ROOT))

from web.backend import schemas as web_schemas


MODEL_ORDER = [
    "SessionInfo",
    "HealthInfo",
    "TodayItem",
    "TodayItemsResponse",
    "FutureItemsResponse",
    "IterationCandidateItem",
    "IterationCandidatesResponse",
    "TaskRunResponse",
    "TaskSubmitResponse",
    "TaskStatusResponse",
    "TaskCancelResponse",
    # Task event union variants — must be declared before TaskEvent itself
    "RowState",
    "LogEvent",
    "StatusEvent",
    "HeartbeatEvent",
    "ProgressEvent",
    "RowStatusEvent",
    "TaskEvent",
    "WordNoteSummary",
    "WordsListResponse",
    "WordNoteDetail",
    "WordIteration",
    "WordIterationsResponse",
    "StatsSummary",
    "SyncConflict",
    "SyncStatusResponse",
    "SyncFlushResponse",
    "SyncRetryResponse",
    "UserProfile",
    "UsersListResponse",
    "ProfileCreateRequest",
    "ProfileCreateResponse",
    "WizardCreateRequest",
    "WizardValidationResult",
    "WizardCreateResponse",
    "ValidateRequest",
    "ValidateResponse",
    "PreflightCheck",
    "PreflightResponse",
]


def _resolve_ref(ref: str, defs: dict[str, Any]) -> dict[str, Any]:
    if not ref.startswith("#/$defs/"):
        return {}
    name = ref.split("/")[-1]
    return defs.get(name, {})


def _schema_to_ts(schema: dict[str, Any], defs: dict[str, Any]) -> str:
    if schema is True:
        return "unknown"
    if schema is False:
        return "never"
    if not schema:
        return "unknown"

    if "$ref" in schema:
        return schema["$ref"].split("/")[-1]

    # RootModel discriminated union → emit `A | B | ...`
    if "oneOf" in schema:
        parts = [_schema_to_ts(p, defs) for p in schema["oneOf"]]
        return " | ".join(parts) if parts else "unknown"

    if "anyOf" in schema:
        parts = [_schema_to_ts(p, defs) for p in schema["anyOf"]]
        dedup = []
        for p in parts:
            if p not in dedup:
                dedup.append(p)
        return " | ".join(dedup) if dedup else "unknown"

    # Pydantic Literal["x"] 字段
    if "const" in schema:
        return f"'{schema['const']}'"

    typ = schema.get("type")
    if typ == "null":
        return "null"
    if typ == "string":
        enum = schema.get("enum")
        if enum:
            return " | ".join(f"'{v}'" for v in enum)
        return "string"
    if typ == "integer" or typ == "number":
        return "number"
    if typ == "boolean":
        return "boolean"
    if typ == "array":
        return f"{_schema_to_ts(schema.get('items', {}), defs)}[]"
    if typ == "object":
        additional = schema.get("additionalProperties")
        if additional is not None:
            return f"Record<string, {_schema_to_ts(additional, defs)}>"
        props = schema.get("properties", {})
        required = set(schema.get("required", []))
        if not props:
            return "Record<string, unknown>"
        lines = ["{"]
        for key, prop in props.items():
            optional = "" if key in required else "?"
            lines.append(f"  {key}{optional}: {_schema_to_ts(prop, defs)}")
        lines.append("}")
        return "\n".join(lines)

    if "enum" in schema:
        return " | ".join(f"'{v}'" for v in schema["enum"])

    return "unknown"


def _collect_model(name: str) -> type[BaseModel]:
    model = getattr(web_schemas, name, None)
    if model is None:
        raise RuntimeError(f"Model not found: {name}")
    if not isinstance(model, type) or not issubclass(model, BaseModel):
        raise RuntimeError(f"Not a pydantic model: {name}")
    return model


def generate_types() -> str:
    lines: list[str] = []
    lines.append("/**")
    lines.append(" * AUTO-GENERATED by scripts/generate_frontend_types.py")
    lines.append(" * Source of truth: web/backend/schemas.py")
    lines.append(" */")
    lines.append("")
    lines.append("export interface ApiResponse<T = unknown> {")
    lines.append("  ok: boolean")
    lines.append("  data: T | null")
    lines.append("  error: { code: string; message: string } | null")
    lines.append("  user_id: string")
    lines.append("}")
    lines.append("")

    rendered: set[str] = set()
    for name in MODEL_ORDER:
        if name in rendered:
            continue
        model = _collect_model(name)
        schema = model.model_json_schema(ref_template="#/$defs/{model}")
        defs = schema.get("$defs", {})
        ts_type = _schema_to_ts(schema, defs)
        if ts_type.startswith("{"):
            lines.append(f"export interface {name} {ts_type}")
        else:
            lines.append(f"export type {name} = {ts_type}")
        lines.append("")
        rendered.add(name)

    return "\n".join(lines).rstrip() + "\n"


def main() -> int:
    parser = argparse.ArgumentParser(description="Generate frontend TypeScript types from backend schemas")
    parser.add_argument(
        "--output",
        default="web/frontend/src/api/types.ts",
        help="Output file path",
    )
    args = parser.parse_args()

    content = generate_types()
    output = Path(args.output)
    output.parent.mkdir(parents=True, exist_ok=True)
    output.write_text(content, encoding="utf-8")
    print(f"Types generated: {output}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
