/**
 * AUTO-GENERATED by scripts/generate_frontend_types.py
 * Source of truth: web/backend/schemas.py
 */

export interface ApiResponse<T = unknown> {
  ok: boolean
  data: T | null
  error: { code: string; message: string } | null
  user_id: string
}

export interface SessionInfo {
  active_profile: string
  available_profiles?: string[]
  server_time: string
  host_binding?: string
}

export interface HealthInfo {
  status?: string
  version?: string
  db_sync?: {
    syncing: boolean
    phase?: string
    started_at?: number
  }
}

export interface TodayItem {
  voc_id: string
  voc_spelling: string
  voc_meanings?: string
  review_count?: number
  familiarity_short?: number
  status?: string | null
}

export interface TodayItemsResponse {
  count?: number
  items?: TodayItem[]
  ts?: number
}

export interface FutureItemsResponse {
  days?: number
  count?: number
  items?: TodayItem[]
}

export interface IterationCandidateItem {
  voc_id: string
  voc_spelling: string
  voc_meanings?: string
  it_level?: number
  weak_score?: number
}

export interface IterationCandidatesResponse {
  count?: number
  items?: IterationCandidateItem[]
}

export interface TaskRunResponse {
  task_id?: string | null
  word_count?: number | null
  days?: number | null
  message?: string | null
}

export interface TaskSubmitResponse {
  task_id: string
}

export interface TaskStatusResponse {
  task_id: string
  status: string
  result?: unknown | null
  error?: string | null
  created_at?: number
  started_at?: number | null
  finished_at?: number | null
}

export interface TaskCancelResponse {
  canceled?: boolean
}

export interface TaskListItem {
  task_id: string
  status: string
  task_type?: string
  profile?: string
  created_at?: number
  started_at?: number | null
  finished_at?: number | null
  error?: string | null
}

export interface TaskListResponse {
  tasks?: TaskListItem[]
  total?: number
}

export interface RowState {
  item_id: string
  status: 'pending' | 'running' | 'done' | 'error' | 'warning'
  phase?: string | null
  error?: string | null
  error_type?: string | null
  error_code?: string | null
  current?: number | null
  total?: number | null
}

export interface LogEvent {
  type: 'log'
  level: 'info' | 'warning' | 'error'
  message: string
  module?: string
  ts: number
}

export interface StatusEvent {
  type: 'status'
  status: 'pending' | 'running' | 'done' | 'error' | 'canceled'
  error?: string | null
  cancel_requested?: boolean | null
  ts: number
}

export interface HeartbeatEvent {
  type: 'heartbeat'
  ts: number
}

export interface ProgressEvent {
  type: 'progress'
  phase: string
  current?: number
  total?: number
  message?: string | null
  ts: number
}

export interface RowStatusEvent {
  type: 'row_status'
  rows: RowState[]
  ts: number
}

export type TaskEvent = LogEvent | StatusEvent | HeartbeatEvent | ProgressEvent | RowStatusEvent

export interface WordNoteSummary {
  voc_id: string
  spelling?: string
  basic_meanings?: string
  memory_aid?: string
  it_level?: number
  sync_status?: number
  created_at?: string
}

export interface WordsListResponse {
  total?: number
  page?: number
  page_size?: number
  items?: WordNoteSummary[]
}

export interface WordNoteDetail {
  voc_id: string
  spelling?: string
  basic_meanings?: string
  memory_aid?: string
  it_level?: number
  sync_status?: number
  created_at?: string
  ielts_focus?: string
  collocations?: string
  traps?: string
  synonyms?: string
  discrimination?: string
  example_sentences?: string
  word_ratings?: string
  tags?: string
  raw_full_text?: string
  it_history?: string
}

export interface WordIteration {
  voc_id: string
  iteration_type: string
  score?: number
  justification?: string
  tags?: string
  refined_content?: string
  raw_response?: string
  created_at?: string
}

export interface WordIterationsResponse {
  voc_id: string
  iterations?: WordIteration[]
}

export interface StatsSummary {
  total_words?: number
  processed_words?: number
  ai_batches?: number
  ai_notes_count?: number
  total_tokens?: number
  avg_latency_ms?: number
  sync_queue_depth?: number
  weak_words_count?: number
  degraded?: boolean
  degraded_reason?: string | null
}

export interface FailureHotspot {
  error_type: string
  error_code?: string | null
  count?: number
  latest_at?: number
  sample_items?: Record<string, unknown>[]
}

export interface OpsStatsResponse {
  tasks_running?: number
  tasks_done_1h?: number
  tasks_error_1h?: number
  recent_tasks?: TaskListItem[]
  failure_hotspots?: FailureHotspot[]
  system_ok?: boolean
  health_checks?: PreflightCheck[]
  sync_queue_depth?: number
  sync_conflict_count?: number
  avg_latency_ms?: number
  degraded?: boolean
  degraded_reason?: string | null
}

export interface MetricPercentiles {
  p50?: number | null
  p95?: number | null
  p99?: number | null
  count?: number
}

export interface OpsMetricsResponse {
  profile: string
  api?: MetricPercentiles
  db_batch_write?: MetricPercentiles
  db_idle_sync?: MetricPercentiles
  sync_queue_depth?: MetricPercentiles
  sync_task?: MetricPercentiles
  window_ttl_s?: number
  is_active_profile?: boolean
}

export interface OpsMetricsResetResponse {
  profile?: string | null
  cleared?: boolean
}

export interface SyncConflict {
  voc_id: string
  spelling?: string
  basic_meanings?: string
  sync_status?: number
  created_at?: string
  match_confidence?: number | null
  match_reason?: string | null
}

export interface SyncStatusResponse {
  queue_depth?: number
  conflict_count?: number
  conflicts?: SyncConflict[]
  failed_count?: number
  failed_items?: SyncConflict[]
  degraded?: boolean
  degraded_reason?: string | null
}

export interface SyncFlushResponse {
  flushed?: boolean
}

export interface SyncRetryResponse {
  retried?: number
  total_conflicts?: number | null
  total_failed?: number | null
  message?: string | null
}

export interface DbReplicaHealthResponse {
  connection_alive: boolean
  is_cloud: boolean
  db_path: string
  sync_in_progress: boolean
  last_sync_phase: string
  sync_p50_ms: number | null
  sync_p95_ms: number | null
  sync_p99_ms: number | null
  sync_count: number
  write_queue_depth: number
  write_total_queued: number
  write_total_written: number
  write_total_errors: number
  schema_version: number
  db_size_mb: number
}

export interface UserProfile {
  username: string
  ai_provider?: string
  has_momo_token?: boolean
  has_ai_key?: boolean
  is_active?: boolean
}

export interface UsersListResponse {
  users?: UserProfile[]
  active_profile: string
}

export interface ProfileCreateRequest {
  profile_name: string
}

export interface ProfileCreateResponse {
  profile_name: string
  profile_path: string
  message: string
}

export interface WizardCreateRequest {
  username: string
  momo_token: string
  ai_provider: string
  ai_api_key: string
  user_email?: string | null
}

export interface WizardValidationResult {
  ok: boolean
  category?: string | null
  detail?: string | null
}

export interface WizardCreateResponse {
  username: string
  profile_path: string
  cloud_configured?: boolean
  validation?: Record<string, WizardValidationResult>
  message: string
}

export interface ValidateRequest {
  field: string
  value: string
}

export interface ValidateResponse {
  field: string
  valid: boolean
  message: string
}

export interface PreflightCheck {
  name: string
  ok: boolean
  status: string
  blocking: boolean
  category: string
  detail: string
  fix_hint: string
}

export interface PreflightResponse {
  username: string
  root_dir: string
  profile_path: string
  force_cloud_mode: boolean
  ok: boolean
  checks?: PreflightCheck[]
  blocking_items?: PreflightCheck[]
}
