/**
 * AUTO-GENERATED by scripts/generate_frontend_types.py
 * Source of truth: web/backend/schemas.py
 */

export interface ApiResponse<T = unknown> {
  ok: boolean
  data: T | null
  error: { code: string; message: string } | null
  user_id: string
}

export interface SessionInfo {
  active_profile: string
  available_profiles?: string[]
  server_time: string
  host_binding?: string
}

export interface HealthInfo {
  status?: string
  version?: string
}

export interface TodayItem {
  voc_id: string
  voc_spelling: string
  voc_meanings?: string
  review_count?: number
  familiarity_short?: number
  status?: string | null
}

export interface TodayItemsResponse {
  count?: number
  items?: TodayItem[]
  ts?: number
}

export interface FutureItemsResponse {
  days?: number
  count?: number
  items?: TodayItem[]
}

export interface IterationCandidateItem {
  voc_id: string
  voc_spelling: string
  voc_meanings?: string
  it_level?: number
  weak_score?: number
}

export interface IterationCandidatesResponse {
  count?: number
  items?: IterationCandidateItem[]
}

export interface TaskRunResponse {
  task_id?: string | null
  word_count?: number | null
  days?: number | null
  message?: string | null
}

export interface TaskSubmitResponse {
  task_id: string
}

export interface TaskStatusResponse {
  task_id: string
  status: string
  result?: unknown | null
  error?: string | null
  created_at?: number
  started_at?: number | null
  finished_at?: number | null
}

export interface TaskCancelResponse {
  canceled?: boolean
}

export interface RowState {
  item_id: string
  status: 'pending' | 'running' | 'done' | 'error' | 'warning'
  phase?: string | null
  error?: string | null
  error_type?: string | null
  error_code?: string | null
  current?: number | null
  total?: number | null
}

export interface LogEvent {
  type: 'log'
  level: 'info' | 'warning' | 'error'
  message: string
  module?: string
  ts: number
}

export interface StatusEvent {
  type: 'status'
  status: 'pending' | 'running' | 'done' | 'error' | 'canceled'
  error?: string | null
  cancel_requested?: boolean | null
  ts: number
}

export interface HeartbeatEvent {
  type: 'heartbeat'
  ts: number
}

export interface ProgressEvent {
  type: 'progress'
  phase: string
  current?: number
  total?: number
  message?: string | null
  ts: number
}

export interface RowStatusEvent {
  type: 'row_status'
  rows: RowState[]
  ts: number
}

export type TaskEvent = LogEvent | StatusEvent | HeartbeatEvent | ProgressEvent | RowStatusEvent

export interface WordNoteSummary {
  voc_id: string
  spelling?: string
  basic_meanings?: string
  memory_aid?: string
  it_level?: number
  sync_status?: number
  created_at?: string
}

export interface WordsListResponse {
  total?: number
  page?: number
  page_size?: number
  items?: WordNoteSummary[]
}

export interface WordNoteDetail {
  voc_id: string
  spelling?: string
  basic_meanings?: string
  memory_aid?: string
  it_level?: number
  sync_status?: number
  created_at?: string
  ielts_focus?: string
  collocations?: string
  traps?: string
  synonyms?: string
  discrimination?: string
  example_sentences?: string
  word_ratings?: string
  tags?: string
  raw_full_text?: string
  it_history?: string
}

export interface WordIteration {
  voc_id: string
  iteration_type: string
  score?: number
  justification?: string
  tags?: string
  refined_content?: string
  raw_response?: string
  created_at?: string
}

export interface WordIterationsResponse {
  voc_id: string
  iterations?: WordIteration[]
}

export interface StatsSummary {
  total_words?: number
  processed_words?: number
  ai_batches?: number
  ai_notes_count?: number
  total_tokens?: number
  avg_latency_ms?: number
  sync_queue_depth?: number
  weak_words_count?: number
}

export interface SyncConflict {
  voc_id: string
  spelling?: string
  basic_meanings?: string
  sync_status?: number
  created_at?: string
}

export interface SyncStatusResponse {
  queue_depth?: number
  conflict_count?: number
  conflicts?: SyncConflict[]
}

export interface SyncFlushResponse {
  flushed?: boolean
}

export interface SyncRetryResponse {
  retried?: number
  total_conflicts?: number | null
  message?: string | null
}

export interface UserProfile {
  username: string
  ai_provider?: string
  has_momo_token?: boolean
  has_ai_key?: boolean
  is_active?: boolean
}

export interface UsersListResponse {
  users?: UserProfile[]
  active_profile: string
}

export interface ProfileCreateRequest {
  profile_name: string
}

export interface ProfileCreateResponse {
  profile_name: string
  profile_path: string
  message: string
}

export interface WizardCreateRequest {
  username: string
  momo_token: string
  ai_provider: string
  ai_api_key: string
  user_email?: string | null
}

export interface WizardValidationResult {
  ok: boolean
  category?: string | null
  detail?: string | null
}

export interface WizardCreateResponse {
  username: string
  profile_path: string
  cloud_configured?: boolean
  validation?: Record<string, WizardValidationResult>
  message: string
}

export interface ValidateRequest {
  field: string
  value: string
}

export interface ValidateResponse {
  field: string
  valid: boolean
  message: string
}

export interface PreflightCheck {
  name: string
  ok: boolean
  status: string
  blocking: boolean
  category: string
  detail: string
  fix_hint: string
}

export interface PreflightResponse {
  username: string
  root_dir: string
  profile_path: string
  force_cloud_mode: boolean
  ok: boolean
  checks?: PreflightCheck[]
  blocking_items?: PreflightCheck[]
}
